server:
  port: 8080

spring:
  datasource:
    username: dev
    password: 123456
    url: jdbc:postgresql://localhost:5432/product_catalog
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
    generate-ddl: true

